// Code generated by go-swagger; DO NOT EDIT.

// Package apiserver musicbot
//
//	The api serving the musicbot functionality.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - application/vnd.api+json
//	  - application/x-www-form-urlencoded
//
//	Produces:
//	  - application/json
//	  - application/vnd.api+json
//
// swagger:meta
package apiserver
