package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/r3boot/go-musicbot/models"
)

/*PostDjplusYidOK Youtube ID was succesfully added to the download queue

swagger:response postDjplusYidOK
*/
type PostDjplusYidOK struct {
}

// NewPostDjplusYidOK creates PostDjplusYidOK with default headers values
func NewPostDjplusYidOK() *PostDjplusYidOK {
	return &PostDjplusYidOK{}
}

// WriteResponse to the client
func (o *PostDjplusYidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*PostDjplusYidNotFound Unable to download Youtube ID

swagger:response postDjplusYidNotFound
*/
type PostDjplusYidNotFound struct {
}

// NewPostDjplusYidNotFound creates PostDjplusYidNotFound with default headers values
func NewPostDjplusYidNotFound() *PostDjplusYidNotFound {
	return &PostDjplusYidNotFound{}
}

// WriteResponse to the client
func (o *PostDjplusYidNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*PostDjplusYidInternalServerError An unexpected error occurred

swagger:response postDjplusYidInternalServerError
*/
type PostDjplusYidInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostDjplusYidInternalServerError creates PostDjplusYidInternalServerError with default headers values
func NewPostDjplusYidInternalServerError() *PostDjplusYidInternalServerError {
	return &PostDjplusYidInternalServerError{}
}

// WithPayload adds the payload to the post djplus yid internal server error response
func (o *PostDjplusYidInternalServerError) WithPayload(payload *models.Error) *PostDjplusYidInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post djplus yid internal server error response
func (o *PostDjplusYidInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDjplusYidInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
