package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "encoding/json"

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json",
    "application/vnd.api+json",
    "application/x-www-form-urlencoded"
  ],
  "produces": [
    "application/json",
    "application/json; charset=utf-8",
    "application/vnd.api+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A simple API to control a go-musicbot via http.",
    "title": "go-musicbot api",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/djplus/{yid}": {
      "post": {
        "description": "This endpoint allows you to add a youtube link to the download queue",
        "summary": "Youtube ripping endpoint",
        "responses": {
          "200": {
            "description": "Youtube ID was succesfully added to the download queue"
          },
          "404": {
            "$ref": "#/responses/UnableToDownloadYIDResponse"
          },
          "500": {
            "$ref": "#/responses/Standard500ErrorResponse"
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/yid"
        }
      ]
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "detail": {
          "type": "string",
          "maxLength": 512,
          "minLength": 1
        },
        "source": {
          "$ref": "#/definitions/ErrorPointer"
        },
        "status": {
          "type": "string",
          "maxLength": 3,
          "minLength": 3,
          "pattern": "^[2345][0-9]{2}$"
        }
      }
    },
    "ErrorPointer": {
      "type": "object",
      "properties": {
        "pointer": {
          "type": "string",
          "maxLength": 128,
          "minLength": 1
        }
      }
    }
  },
  "parameters": {
    "yid": {
      "maxLength": 11,
      "minLength": 11,
      "pattern": "[a-zA-Z0-9_-]{11}",
      "type": "string",
      "description": "Youtube ID, needs to point to a single video",
      "name": "yid",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "Standard500ErrorResponse": {
      "description": "An unexpected error occurred",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "UnableToDownloadYIDResponse": {
      "description": "Unable to download Youtube ID"
    }
  }
}`))
}
