FROM alpine:edge
MAINTAINER Lex van Roon <r3boot@r3blog.nl>

RUN apk update \
    && apk upgrade \
    && apk add git go make musl-dev

COPY files/build.sh /build.sh
USER root
ENTRYPOINT ["/build.sh"]
CMD [""]
