// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Download download
//
// swagger:model Download
type Download struct {

	// submitter
	// Required: true
	// Max Length: 128
	// Min Length: 1
	Submitter *string `json:"submitter"`

	// yid
	// Required: true
	// Max Length: 11
	// Min Length: 11
	// Pattern: [a-zA-Z0-9_-]{11}
	Yid *string `json:"yid"`
}

// Validate validates this download
func (m *Download) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubmitter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateYid(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Download) validateSubmitter(formats strfmt.Registry) error {

	if err := validate.Required("submitter", "body", m.Submitter); err != nil {
		return err
	}

	if err := validate.MinLength("submitter", "body", *m.Submitter, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("submitter", "body", *m.Submitter, 128); err != nil {
		return err
	}

	return nil
}

func (m *Download) validateYid(formats strfmt.Registry) error {

	if err := validate.Required("yid", "body", m.Yid); err != nil {
		return err
	}

	if err := validate.MinLength("yid", "body", *m.Yid, 11); err != nil {
		return err
	}

	if err := validate.MaxLength("yid", "body", *m.Yid, 11); err != nil {
		return err
	}

	if err := validate.Pattern("yid", "body", *m.Yid, `[a-zA-Z0-9_-]{11}`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this download based on context it is used
func (m *Download) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Download) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Download) UnmarshalBinary(b []byte) error {
	var res Download
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
