// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Elapsed elapsed
//
// swagger:model Elapsed
type Elapsed int64

// Validate validates this elapsed
func (m Elapsed) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinimumInt("", "body", int64(m), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("", "body", int64(m), 65535, false); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this elapsed based on context it is used
func (m Elapsed) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
