// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Filename filename
//
// swagger:model Filename
type Filename string

// Validate validates this filename
func (m Filename) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 16); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 1024); err != nil {
		return err
	}

	if err := validate.Pattern("", "body", string(m), `.*[a-zA-Z0-9_-]{11}.mp3`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this filename based on context it is used
func (m Filename) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
