// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ID Id
//
// swagger:model Id
type ID int64

// Validate validates this Id
func (m ID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Id based on context it is used
func (m ID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
