// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Query query
//
// swagger:model Query
type Query string

// Validate validates this query
func (m Query) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 128); err != nil {
		return err
	}

	if err := validate.Pattern("", "body", string(m), `[a-zA-Z0-9_-]{1,128}`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this query based on context it is used
func (m Query) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
